// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'CatalogConteiner': string;
  'btnOrder': string;
  'catalog': string;
  'catalogTitle': string;
  'catalogWrapper': string;
  'go-left-right': string;
  'itemBoock': string;
}
export const cssExports: CssExports;
export default cssExports;
