// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btnCardOrder': string;
  'card': string;
  'cardAbout': string;
  'cardBoock': string;
  'cardConteiner': string;
  'imgBoockBlock': string;
  'infoBoockBlock': string;
  'infoCard': string;
  'starsCard': string;
}
export const cssExports: CssExports;
export default cssExports;
