// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btnAbout': string;
  'btnCatalog': string;
  'btnCatalogConteiner': string;
  'btnContacts': string;
  'header': string;
  'headerConteiner': string;
  'iconBlock': string;
  'menuBlock': string;
}
export const cssExports: CssExports;
export default cssExports;
