// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn': string;
  'closeOrderBtnCard': string;
  'imgWrapper': string;
  'infoWrapper': string;
  'mainBody': string;
  'mainTitle': string;
  'modal': string;
  'modalCard': string;
  'orderBtnCard': string;
}
export const cssExports: CssExports;
export default cssExports;
